# Generated by Django 5.2 on 2025-09-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_content_post_price_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
